version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user_wp
      MYSQL_PASSWORD: password_wp
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_wp

  wordpress:
    image: wordpress:latest
    container_name: wordpress_site
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user_wp
      WORDPRESS_DB_PASSWORD: password_wp
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp_content:/var/www/html
    networks:
      - red_wp
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_gestor
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - red_wp
    depends_on:
      - db

volumes:
  db_data:


networks:
  red_wp:
    driver: bridge